For each language L1 - L3 I have put everything needed to compile a program (omitting correctness proofs) in a file called compile.v
L1_MalechaQuoted/compile.v
L1_5_box/compile.v
L2_typeStripped/compile.v
L3_flattenedApp/compile.v

(Actually, L2 still requires two other files: term.v and program.v,
but I will fix that.)

I updated _CoqProject, and went to compile the entire project.  L1 -
L3 compiled, but

------------------
File "./L4_deBruijn/L3_to_L4.v", line 162, characters 13-39:
Error: The reference malecha_L1.program_Program was not found in the current
------------------

In the best of all worlds, L4 should only look at L3, (and now, I'm
hoping, only at L3.compile.v).

I did change a lot of things around, and program_Program is now in
L1.compile.v instead of in malecha_L1.v. 

L3.unaryApplications.v has long had a program_Program that went from
L0 (Malecha's quoted Coq) to L3.  That old version, also used some
things from L2.  I hope I've now fixed that.

So, again, I'd like to see L3_to_L4.v use only L3.compile.v

Matthieu, let me know if there is a problem with this.